server:
  port: ${PORT:8080}

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

app:
  r2dbc:
    postgres:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      database: ${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      pool:
        initial-size: 5
        max-size: 20